[package]
name = "tokio-uring"
version = "0.3.0"
authors = ["Tokio Contributors <team@tokio.rs>"]
edition = "2018"
readme = "README.md"
license = "MIT"
documentation = "https://docs.rs/tokio-uring/0.3.0/tokio-uring"
repository = "https://github.com/tokio-rs/tokio-uring"
homepage = "https://tokio.rs"
description = """
io-uring support for the Tokio asynchronous runtime.
"""
categories = ["asynchronous", "network-programming"]
keywords = ["async", "fs", "io-uring"]

# Sanity checks normally enabled in debug builds can be enabled in release builds too
# by using the 'cautious' feature.
# At the moment, the only such sanity check is for buffer IDs coming from the kernel
# and being released back to the kernel when buffer groups are being used for read and receive
# operations. No benchmarks yet show whether these sanity checks are too time consuming in
# normal operation but they do cause more memory to be allocated, acting as a bitmask.
# This feature is likely to be temporary.
#
# Useful when building the "buf_ring_tcp" example. Cargo doesn't seem to allow it to be set by
# default. Cargo issue #4663.

[features]
cautious = []

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.2", features = ["net", "rt"] }
scoped-tls = "1.0.0"
slab = "0.4.2"
libc = "0.2.80"

## WARNING!!! Don't actually merge this. This PR was for demonstration purposes only.
## The standard io-uring has not been updated with the register and unregister commands
## for buffer rings yet.
#io-uring = { version = "0.5.0", features = [ "unstable" ] }
io-uring = { git = "https://github.com/frankreh/io-uring", branch = "tokio-uring-wip1", features = ["unstable"] }


socket2 = { version = "0.4.4", features = [ "all"] }
bytes = { version = "1.0", optional = true }

[dev-dependencies]
clap = { version = "4.0.15", features = ["derive"] }
tempfile = "3.2.0"
tokio-test = "0.4.2"
iai = "0.1.1"
futures = "0.3.25"
criterion = "0.4.0"

[package.metadata.docs.rs]
all-features = true

[[bench]]
name = "lai_no_op"
path = "benches/lai/no_op.rs"
harness = false

[[bench]]
name = "criterion_no_op"
path = "benches/criterion/no_op.rs"
harness = false
